# Generated by Django 4.1.3 on 2022-11-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('total_proteins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_calories', models.IntegerField()),
                ('image', models.ImageField(upload_to='meals/')),
                ('products', models.ManyToManyField(to='meals.product')),
            ],
        ),
    ]
