# Generated by Django 4.1.3 on 2022-11-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_options_meal_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
